export const upcomingEvents = [
  {
    title: "AI & Machine Learning Workshop",
    description:
      "An interactive workshop on AI and ML fundamentals with hands-on coding exercises.",
    date: "March 15, 2025",
    time: "10:00 AM - 4:00 PM",
    location: "BITS Pilani, Main Auditorium",
    eventType: "Workshop",
    duration: "6 hours",
    guestSpeakers: [
      { name: "Dr. Anil Mehta", designation: "Google AI Researcher" },
      { name: "Priya Sharma", designation: "ML Engineer at Microsoft" },
    ],
    organizer: "Computer Science Club, BITS Pilani",
    contactEmail: "csclub@bits-pilani.ac.in",
    contactPhone: "+91 9876543210",
    isRegistrationOpen: true,
    registrationLink: "https://bit.ly/ai-ml-workshop",
    imageUrl: "https://example.com/ai-ml-workshop-banner.jpg",
    tags: [
      { title: "AI", icon: "brain-circuit" },
      { title: "Machine Learning", icon: "cpu" },
      { title: "Coding", icon: "code" },
    ],
  },
  {
    title: "Web Dev Bootcamp",
    description:
      "Learn how to build modern web applications with Next.js and TypeScript.",
    date: "March 25, 2025",
    time: "9:00 AM - 5:00 PM",
    location: "Innovation Lab, BITS Pilani",
    eventType: "Bootcamp",
    duration: "8 hours",
    guestSpeakers: [
      { name: "Rajesh Verma", designation: "Full Stack Developer at Amazon" },
    ],
    organizer: "Web Development Society",
    contactEmail: "webdev@bits-pilani.ac.in",
    contactPhone: "+91 9876543211",
    isRegistrationOpen: true,
    registrationLink: "https://bit.ly/web-dev-bootcamp",
    imageUrl: "https://example.com/web-dev-bootcamp-banner.jpg",
    tags: [
      { title: "Web Development", icon: "globe" },
      { title: "Next.js", icon: "layers" },
      { title: "TypeScript", icon: "file-code" },
    ],
  },
  {
    title: "Cybersecurity and Ethical Hacking",
    description:
      "Explore ethical hacking techniques and cybersecurity fundamentals.",
    date: "April 5, 2025",
    time: "11:00 AM - 3:00 PM",
    location: "Cyber Lab, BITS Pilani",
    eventType: "Seminar",
    duration: "4 hours",
    guestSpeakers: [
      { name: "Kunal Singh", designation: "Cybersecurity Analyst, IBM" },
    ],
    organizer: "Cybersecurity Club",
    contactEmail: "cyberclub@bits-pilani.ac.in",
    contactPhone: "+91 9876543212",
    isRegistrationOpen: false,
    registrationLink: null,
    imageUrl: "https://example.com/cybersecurity-seminar.jpg",
    tags: [
      { title: "Cybersecurity", icon: "shield" },
      { title: "Ethical Hacking", icon: "bug" },
    ],
  },
];

export const previousEvents = [
  {
    title: "BITS Hackathon 2024",
    description:
      "A 24-hour coding marathon where students built innovative tech solutions.",
    date: "February 10, 2024",
    time: "9:00 AM - 9:00 AM (Next Day)",
    location: "BITS Pilani, Innovation Hall",
    eventType: "Hackathon",
    duration: "24 hours",
    guestSpeakers: [
      { name: "Google Team", designation: "Software Engineers" },
      { name: "Microsoft Panel", designation: "Cloud Experts" },
      { name: "OpenAI Representatives", designation: "AI Specialists" },
    ],
    organizer: "BITS Pilani Tech Club",
    contactEmail: "hackathon@bits-pilani.ac.in",
    contactPhone: "+91 9876543213",
    isRegistrationOpen: false,
    registrationLink: null,
    imageUrl: "https://example.com/bits-hackathon-2024.jpg",
    tags: [
      { title: "Hackathon", icon: "activity" },
      { title: "Coding", icon: "code" },
      { title: "Innovation", icon: "lightbulb" },
    ],
  },
  {
    title: "Blockchain & Crypto Seminar",
    description:
      "A deep dive into blockchain technology and the future of cryptocurrency.",
    date: "January 18, 2024",
    time: "2:00 PM - 6:00 PM",
    location: "Seminar Hall, BITS Pilani",
    eventType: "Seminar",
    duration: "4 hours",
    guestSpeakers: [
      { name: "Ankit Raj", designation: "Blockchain Developer at Polygon" },
    ],
    organizer: "Finance & Tech Club",
    contactEmail: "blockchain@bits-pilani.ac.in",
    contactPhone: "+91 9876543214",
    isRegistrationOpen: false,
    registrationLink: null,
    imageUrl: "https://example.com/blockchain-seminar.jpg",
    tags: [
      { title: "Blockchain", icon: "database" },
      { title: "Cryptocurrency", icon: "dollar-sign" },
    ],
  },
  {
    title: "Game Development with Unity",
    description: "Introduction to game development using Unity and C#.",
    date: "December 5, 2023",
    time: "10:00 AM - 4:00 PM",
    location: "Game Dev Lab, BITS Pilani",
    eventType: "Workshop",
    duration: "6 hours",
    guestSpeakers: [
      { name: "Ramesh Yadav", designation: "Game Developer at Ubisoft" },
    ],
    organizer: "Game Development Society",
    contactEmail: "gamedev@bits-pilani.ac.in",
    contactPhone: "+91 9876543215",
    isRegistrationOpen: false,
    registrationLink: null,
    imageUrl: "https://example.com/game-dev-workshop.jpg",
    tags: [
      { title: "Game Development", icon: "gamepad" },
      { title: "Unity", icon: "package" },
      { title: "C#", icon: "code" },
    ],
  },
];
